name: CI - Build & Tag Docker

on:
  push:
    branches: [ main ]

# Přidáváme práva pro GITHUB_TOKEN (klíč k úspěchu!)
permissions:
  contents: write   # ← Umožní push tagů

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: myApp
          tags: |
            type=raw,value=${{ github.run_id }}

      - name: Build Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}

      - name: Create Git tag
        run: |
          BUILD_ID=${{ github.run_id }}
          git tag myApp/$BUILD_ID
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git push origin myApp/$BUILD_ID
